### ISSUE TITLE
Migrations are missing from pypi package.

### ISSUE THREAD

**Issue by rvanlaar** [dvska/django-admin-ip-whitelist#9]
I added django-admin-ip-whitelist to Django. The migrations aren't included in the pypi package.

**Comment by bkvirendra** [comment]
@rvanlaar This is fixed in one the fork's at https://github.com/bkvirendra/django-admin-ip-whitelist, this will soon be merged in the master. In the meanwhile, feel free to use the fork.

**Comment by rvanlaar** [comment]
Thanks @bkvirendra 

It's working now.
